config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  root 'static_pages#home'
  get 'search' => 'users#search'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:index, :create, :destroy]
  resources :notifications, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @feed_items = current_user.feed.limit(7).order(created_at: 'DESC')
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= link_to '投稿する', new_post_path, class: "btn btn-success" %>
      </section>
      <%= link_to "お気に入りの投稿一覧", likes_path, class: "btn btn-info" %>
      <%= render 'shared/search' %>
      <%= render 'shared/category' %>
    </aside>
    <div class="col-md-8">
      <h3>最近の投稿</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class ="main" >
    <main class="inner">
      <h1 class="cover-heading">沖縄観光スポット投稿サービス</h1>
      <h4>あなたの思う沖縄のおすすめ観光スポットを投稿し共有しましょう</h4>
      <p>新しくアカウントを作成する</p>
      <p class="lead">
        <a href="users/sign_up" class="btn btn-lg btn-primary">Sign Up</a>
      </p>
      <p>すでにアカウントをお持ちの方</p>
      <p><a href="users/sign_in" class="btn btn-lg btn-success">Log in</a></p>
    </main>
  </div>
<% end %>