config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  root 'static_pages#home'
  get 'search' => 'users#search'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:index, :create, :destroy]
  resources :notifications, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_category.html.erb
<div class ="categories">
  <p class ="category">カテゴリー一覧</p>
  <ul>
      <%= link_to 'レジャー', posts_path(category_id: 1) %><br />
      <%= link_to 'グルメ',   posts_path(category_id: 2) %><br />
      <%= link_to 'ホテル・施設系', posts_path(category_id: 3) %><br />
      <%= link_to 'その他', posts_path(category_id: 4) %>
  </ul>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <% else %>
  <h3>投稿はまだありません</h3>
<% end %>

app/views/shared/_search.html.erb
<div class ="search">
  <p>ユーザーまたは投稿を探す</p>
  <%= form_tag(search_path, :method => 'get') do %>
    <%= select_tag(:option, options_for_select([["user", "1"],["post","2"]]), id: "select")%>
    <%= text_field_tag :search %>
    <%= submit_tag 'Search', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.username %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "your posts") %></span>