config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  root 'static_pages#home'
  get 'search' => 'users#search'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:index, :create, :destroy]
  resources :notifications, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  belongs_to :user
  belongs_to :category
  has_one_attached :image
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validates :image,   content_type: {
    in: %w(image/jpeg image/gif image/png),
    message: "must be a valid image format",
  },
                      size: {
                        less_than: 5.megabytes,
                        message: "should be less than 5MB",
                      }

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorlit_users, through: :likes, source: :user
  has_many :notifications, dependent: :destroy

  def display_image
    image.variant(resize_to_limit: [500, 500])
  end

  def favorlit(user)
    likes.create(user_id: user.id)
  end

  def unfavorlit(user)
    likes.find_by(user_id: user.id).destroy
  end

  def favorlit?(user)
    favorlit_users.include?(user)
  end

  def Post.search(search, user_or_post)
    if user_or_post == "2"
      Post.where(['content LIKE ?', "%#{search}%"])
    else
      Post.all
    end
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where([
      "visitor_id = ? and visited_id = ? and post_id = ? and action = ? ",
      current_user.id, user_id, id, 'like',
    ])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).
      distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    # save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: :destroy

  def index
    @category = Category.find(params[:category_id])
    @posts    = @category.posts.all.page(params[:page]).per(15).order(created_at: 'DESC')
  end

  def new
    @post = current_user.posts.build if user_signed_in?
  end

  def show
    @post = Post.find_by(id: params[:id])
    @category = Category.find(@post.category_id)
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      flash[:success] = "投稿しました！"
      redirect_to post_path(@post)
    else
      @feed_items = current_user.feed.page(params[:page])
      render 'posts/new'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = '編集しました'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:info] = "削除しました。"
    redirect_to request.referrer || root_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :image, :category_id, :address)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<% if post.comments.any? %>
  <% post.comments.each do |comment| %>
    <div class="mb-2">
      <% if comment.user == current_user %>
        <%= link_to "delete?", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
      <% end %>
      <span>
        <strong>
          <%= link_to comment.user.username, user_path(comment.user), class: "comment-user" %>
        </strong>
      </span>
      <span><%= comment.comment %></span>
      <div class ="time"><i><%= time_ago_in_words(comment.created_at)%></i> ago</div>
    </div>
  <% end %>
<% else %>
  <p>コメントはまだありません</p>
<% end %>

app/views/posts/_map.html.erb
<h2>gmap</h2>
<div id='map'></div>

<style>
#map {
  height: 400px;
  width: auto;
}
</style>

<script>
let map

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: <%= post.latitude %>, lng: <%= post.longitude %>},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: <%= post.latitude %>, lng: <%= post.longitude %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>

app/views/posts/_post.html.erb
<div class ="flex">
  <li id="posts-<%= post.id %>">
    <%= link_to gravatar_for(post.user, size: 50), post.user %>
    <span class="user"><%= link_to post.user.username, post.user %></span>
    <span class="content">
      <%= post.content %>
      <%= link_to post_path(post) do %>
      <div class ="image">
        <%= image_tag post.display_image if post.image.attached? %>
      </div>
      <% end %>
      <%= render 'likes/like', post: post %>
    </span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(post.created_at) %> ago.
      <% if current_user?(post.user) %>
        <%= link_to "delete", post, method: :delete,
                                           data: { confirm: "You sure?" } %>
      <% end %>
    </span>
  </li>
</div>

app/views/posts/edit.html.erb
<%= provide(:title, 'edit post') %>
<h2>投稿を編集</h2>
<div class ="row">
  <div class ="col-md-8 col-md-offset-2">
    <%= form_with(model: @post, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content, placeholder: "投稿内容を入力..." %>
        <%= f.label :image %>
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", value: '@post.image' %>

        <%= f.label :category_id, "カテゴリ" %>
        <%= f.select :category_id, Category.all.map{|c| [c.name, c.id]},
          include_blank: "選択して下さい" %>

        <%= f.label :address, "所在地" %>
        <%= f.text_field :address %>
      </div>
      <%= f.submit "Update", class: "btn btn-info" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $("#micropost_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#micropost_image").val("");
    }
  });
</script>

app/views/posts/index.html.erb
<% provide(:title, @category.name) %>
<div class ="row">
  <div class ="col-md-12">
    <h2><%= @category.name %>( <%= @posts.count %> )</h2>
    <% if @posts.any? %>
      <%= paginate @posts %>
      <ol class ="micropost">
        <div class ="box">
          <%= render @posts %>
        </div>
      </ol>
      <%= paginate @posts %>
    <% else %>
      <h2><%= @category.name %>の投稿はまだありません</h2>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= provide(:title, 'New post') %>
<h2>新規投稿</h2>
<div class ="row">
  <div class ="col-md-8 col-md-offset-2">
    <%= form_with(model: @post, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content, placeholder: "投稿内容を入力..." %>
        <%= f.label :image %>
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>

        <%= f.label :category_id, "カテゴリ" %>
        <%= f.select :category_id, Category.all.map{|c| [c.name, c.id]},
          include_blank: "選択して下さい" %>

        <%= f.label :address, "所在地" %>
        <%= f.text_field :address %>
      </div>
      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $("#micropost_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#micropost_image").val("");
    }
  });
</script>

app/views/posts/show.html.erb
<%= provide(:title, 'show post') %>
<h2>post detail</h2>
<% if current_user?(@post.user) %>
  <%= link_to '投稿を編集', edit_post_path, class: "btn btn-info" %>
<% end %>
<div class ="row">
  <div class ="col-md-6">
    <div class ="card-left">
      <%= image_tag @post.display_image, class: "card-image" %>
    </div>
    <div class="m-2">
      <p>投稿内容</p>
      <strong>
        <%= @post.content %>
        <div class="post-time"><%= time_ago_in_words(@post.created_at) %> ago</div>
        <hr>
      </strong>
    </div>
    <div class ="post-info"><p>所在地</p><%= @post.address %></div>
    <div class ="post-info"><p>カテゴリ</p><%= @category.name %></div>
  </div>
  <div class ="col-md-6">
    <div class ="card-right">
      <div class ="card-right-name">
        <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
            title: @post.user.username do %>
          <%= gravatar_for @post.user, size: 50 %>
          <strong><%= @post.user.username %></strong>
        <% end %>
      </div>
      <div>
        <strong><p>profile</p></strong>
        <%= @post.user.profile %>
        <hr />
      </div>
      <div class ="card-right-comment">
        <div id="comment-post-<%= @post.id.to_s %>">
          <%= render 'posts/comment', post: @post %>
        </div>
      </div>
      <div id="comment-form-post-<%= @post.id.to_s %>">
        <%= form_with model: [@post, Comment.new],  class: "w-100" do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :post_id, value: @post.id %>
          <%= f.text_field :comment, class: "form-control comment-input", placeholder: "コメント ...", autocomplete: :off,
           id: "comment" %>
          <%= f.submit "コメントする", class: "btn btn-info" %>
        <% end %>
      </div>
      <%= render 'likes/like', post: @post %>
      <%= render 'posts/map', post: @post %>
    </div>
  </div>
</div>