config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  root 'static_pages#home'
  get 'search' => 'users#search'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:index, :create, :destroy]
  resources :notifications, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <i>Copyright @waker 2020</i>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class ="navbar navbar-fixed_top navbar-light" style="background-color: #3399ff;">
<div class ="container">
  <%= link_to "walker", root_path, id: "logo" %>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to "Home", root_path, id: "text" %>
      </li>
      <% if user_signed_in? %>
      <li><%= link_to "check", notifications_path, class: "check", id: "text" %>
        <% if unchecked_notifications.any? %>
          <span class="fa">
            <i class="fa fa-bell faa-ring animated"></i>
          </span>
        <% end %>
      </li>
      <li><%= link_to "Users", users_path, id: "text" %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", profile_edit_path %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </li>
      <% else %>
      <li>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary", id: "text" %>
      </li>
      <li>
        <%= link_to "login", new_user_session_path, class: "btn btn-success", id: "text" %>
      </li>
      <% end %>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class ="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>